Boruta requires numpy<1.24.0 to avoid the error `AttributeError: module 'numpy' has no attribute 'int'` . np.int like functions got deprecated after numpy 1.24.0. -- SO203